name: deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # Required by playwrgith
          node-version: "14"
      - uses: bahmutov/npm-install@v1
      # This is needed when playwright is used in tests #70
      - run: npx playwright install-deps
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn typedoc
      - name: Deploy production 🚀
        if: ${{github.ref == 'refs/heads/main'}}
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./ # The folder the action should deploy.
