name: Snowpack
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Use Node.js 14.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14.x
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint # will run `yarn build` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn test` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test # will run `yarn test` command
      # - run: yarn
      # - run: yarn lint
      # - run: yarn test
      # - run: yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: publish # The folder the action should deploy.
