name: Snowpack
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # Required by playwrgith
          node-version: "14"
      - uses: bahmutov/npm-install@v1
      # This is needed when playwright is used in tests #70
      - run: npx playwright install-deps
      - run: yarn
      - name: Run atomic-server docker image in background (for testing)
        run: nohop docker run -p 80:80 -p 443:443 -v atomic-storage:/atomic-storage joepmeneer/atomic-server --init &
      - run: yarn lint-fix
      - run: nohup yarn start &
      - run: yarn build
      - run: yarn test
      - name: Deploy (`main` branch only) 🚀
        if: github.ref = refs/heads/main
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: data-browser/publish # The folder the action should deploy.
